# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-05-22 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200520_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='tel',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='固定電話'),
        ),
    ]
