# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-06-04 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20200604_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='default_image',
            field=models.ImageField(blank=True, default='', max_length=200, null=True, upload_to='', verbose_name='默認圖片'),
        ),
    ]
